// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6mMfJ1MLz4i6SgoPXiZ6azbFl3wN75HI',
    appId: '1:1054622572850:web:165eb887cb197b66ea372b',
    messagingSenderId: '1054622572850',
    projectId: 'auth-37565',
    authDomain: 'auth-37565.firebaseapp.com',
    storageBucket: 'auth-37565.firebasestorage.app',
    measurementId: 'G-BR5ZKLEXJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbxqZHxqvxJOZ8QnJMWLRDim3aylsTQ7M',
    appId: '1:1054622572850:android:c29cdc8f3f1389b7ea372b',
    messagingSenderId: '1054622572850',
    projectId: 'auth-37565',
    storageBucket: 'auth-37565.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD24uuzjjKCRRAsNazEIEBUxW14tVWU1Kc',
    appId: '1:1054622572850:ios:d3292d54deb1befdea372b',
    messagingSenderId: '1054622572850',
    projectId: 'auth-37565',
    storageBucket: 'auth-37565.firebasestorage.app',
    androidClientId: '1054622572850-j1llcr7lr75fienbiouola8lf56k08gc.apps.googleusercontent.com',
    iosClientId: '1054622572850-q4js4td850jjvlel3bse11j0uso4tq3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieExplorerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD24uuzjjKCRRAsNazEIEBUxW14tVWU1Kc',
    appId: '1:1054622572850:ios:d3292d54deb1befdea372b',
    messagingSenderId: '1054622572850',
    projectId: 'auth-37565',
    storageBucket: 'auth-37565.firebasestorage.app',
    androidClientId: '1054622572850-j1llcr7lr75fienbiouola8lf56k08gc.apps.googleusercontent.com',
    iosClientId: '1054622572850-q4js4td850jjvlel3bse11j0uso4tq3c.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieExplorerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyOjyGrHIcogJlWauo0EwJMUvdgU0VjQk',
    appId: '1:1054622572850:web:c9e2c96d6a06d4c2ea372b',
    messagingSenderId: '1054622572850',
    projectId: 'auth-37565',
    authDomain: 'auth-37565.firebaseapp.com',
    storageBucket: 'auth-37565.firebasestorage.app',
    measurementId: 'G-57G0ZGF9YC',
  );
}
